import type { Metadata } from 'next';

import './globals.css';

import { getFontConfig } from '@/assets/fonts/fonts.config';
const { accent, sans } = getFontConfig();

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" className={`${accent.variable} ${sans.variable}`}>
      <body>{children}</body>
    </html>
  );
};

/**
 * Exports
 */

export const metadata: Metadata = {
  title: 'Konstantin Münster – Freelance Web Developer',
  description: 'Generated by create next app',
};

export default RootLayout;
